// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	dto "library-api/dto"
	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: _a0
func (_m *AuthService) SignIn(_a0 *dto.SignInReq) (*dto.TokenResponse, error) {
	ret := _m.Called(_a0)

	var r0 *dto.TokenResponse
	if rf, ok := ret.Get(0).(func(*dto.SignInReq) *dto.TokenResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*dto.SignInReq) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
