// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	models "git.garena.com/sea-labs-id/trainers/library-api/models"
	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetUsers provides a mock function with given fields: name
func (_m *UserService) GetUsers(name string) ([]*models.User, error) {
	ret := _m.Called(name)

	var r0 []*models.User
	if rf, ok := ret.Get(0).(func(string) []*models.User); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
